# Generated by Django 4.0.6 on 2022-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='unit_size',
            field=models.FloatField(),
        ),
    ]
