# Generated by Django 4.0.6 on 2022-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_app', '0002_alter_medicine_unit_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mrp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit_size',
            field=models.IntegerField(),
        ),
    ]
