# Generated by Django 4.0.6 on 2022-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_app', '0003_alter_medicine_mrp_alter_medicine_unit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit_value',
            field=models.CharField(choices=[('nos', 'NOS'), ('ml', 'ML')], default='nos', max_length=5),
        ),
    ]
